[package]
name = "pwdb"
version = "0.1.0"
authors = ["Tim Kuhlman <tim@backgroundprocess.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
generic-array = "0.14"
sha2 = "0.9"
twofish = "0.4"
